name: Setup Node and Install
description: Setup Node via .nvmrc and install dependencies with npm ci

inputs:
  working-directory:
    description: Optional working directory for install
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
